-- MySQL Script generated by MySQL Workbench
-- Sun Jul 21 12:41:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Courses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `idCourses` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `ects` INT NOT NULL,
  `path` ENUM('core', 'A', 'B') NOT NULL,
  `type` ENUM('obligatory', 'obligatory-by-choice', 'basic') NULL,
  `specificpath` ENUM('E1', 'E2', 'E3', 'E4', 'E5', 'E6') NULL,
  PRIMARY KEY (`idCourses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `idStudents` INT NOT NULL,
  `firstname` VARCHAR(128) NOT NULL,
  `lastname` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`idStudents`),
  CONSTRAINT `fk_Students_Users1`
    FOREIGN KEY (`idStudents`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Students_Users1_idx` ON `mydb`.`Students` (`idStudents` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Students_has_Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students_has_Courses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students_has_Courses` (
  `idStudents` INT NOT NULL,
  `idCourses` INT NOT NULL,
  `grade` DOUBLE NULL,
  PRIMARY KEY (`idStudents`, `idCourses`),
  CONSTRAINT `fk_Students_has_Courses_Students1`
    FOREIGN KEY (`idStudents`)
    REFERENCES `mydb`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_has_Courses_Courses1`
    FOREIGN KEY (`idCourses`)
    REFERENCES `mydb`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Students_has_Courses_Courses1_idx` ON `mydb`.`Students_has_Courses` (`idCourses` ASC) VISIBLE;

CREATE INDEX `fk_Students_has_Courses_Students1_idx` ON `mydb`.`Students_has_Courses` (`idStudents` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
